### PR TITLE
controller, labels:don't take managed-by from CR

### LINKED ISSUE #1051: managed-by label of service-monitor-cluster-network-addons-operator is wrong
**What happened**:

I installed OpenShift 4.10 and observed these labels on service-monitor-cluster-network-addons-operator object.

```
  labels:
    app.kubernetes.io/component: network
    app.kubernetes.io/managed-by: hco-operator
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: v4.10.0
    networkaddonsoperator.network.kubevirt.io/version: sha256_ce0e77c4ee5e28356c359578f7342a3d3690ac0373018605439549e1
    openshift.io/cluster-monitoring: ""
    prometheus.cnao.io: ""
```

**What you expected to happen**:
It must be `app.kubernetes.io/managed-by: cluster-network-addons-operator` 

**Environment**:
OpenShift 4.10

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
When CNAO is deployed by HCO, HCO puts managed-by label with HCO value on
networkAddonsConfig. networkAddonsConfig controller then takes this value and inherit it
to the deployed components. This cause a wrong result of a CNAO component labeled
as managed by HCO.

This commit makes that managed-by label will not be taken from networkAddonsConfig,
and test it against an example component - ovs.

Fixes #1051

**Special notes for your reviewer**:
This PR is initially created by @alonSadan . With his consent I took it and applied some gomega matchers changes

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: test/operations/operations.go [hunk 1]
```diff
@@ -154,3 +154,22 @@ func configSpecToYaml(configSpec cnao.NetworkAddonsConfigSpec) string {
...
+func LabelConfig(gvk schema.GroupVersionKind, newLabels map[string]string) {
+	By(fmt.Sprintf("Labeling NetworkAddonsConfig with:\n%v", newLabels))
+
+	// Get current Config
+	config := GetConfig(gvk)
+
+	// Label the Config with the desired new labels
+	labels := config.GetLabels()
+	if labels == nil {
+		labels = make(map[string]string)
```
Comment (oshoval) [inline test/operations/operations.go:167]: if there were not labels before then maybe we can do directly
config.SetLabels(labels) ?

File: test/e2e/workflow/deployment_test.go [hunk 2]
```diff
@@ -454,6 +455,124 @@ var _ = Describe("NetworkAddonsConfig", func() {
...
+			}
+
+			CreateConfig(gvk, configSpec)
+			CheckConfigCondition(gvk, ConditionAvailable, ConditionTrue, 15*time.Minute, CheckDoNotRepeat)
+		})
+
+		getDaemonsetLabels := func(ds *v1.DaemonSet) map[string]string { return ds.GetLabels() }
+		getDaemonsetTemplateLabels := func(ds *v1.DaemonSet) map[string]string { return ds.Spec.Template.GetLabels() }
+		getDeploymentLabels := func(ds *v1.Deployment) map[string]string { return ds.GetLabels() }
+		getDeploymentTemplateLabels := func(ds *v1.Deployment) map[string]string { return ds.Spec.Template.GetLabels() }
```
Comment (oshoval) [inline test/e2e/workflow/deployment_test.go:479]: Please consider making those regular functions

File: test/e2e/workflow/deployment_test.go [hunk 3]
```diff
@@ -454,6 +455,124 @@ var _ = Describe("NetworkAddonsConfig", func() {
...
+					WithTransform(getDaemonsetTemplateLabels, HaveKeyWithValue(names.MANAGED_BY_LABEL_KEY, managedByLabelComponentVal))),
+					"Daemonset should have been labeled with `managed-by` label with value %s", managedByLabelComponentVal)
+
+				LabelConfig(gvk, labels)
+				Eventually(func() map[string]string {
+					return GetConfig(gvk).GetLabels()
+				}, 2*time.Minute, time.Minute).Should(HaveKeyWithValue(names.MANAGED_BY_LABEL_KEY, managedByLabelCRVal),"should succeed setting labels on NetworkAddonsConfig")
+			})
+
+			It("Should NOT apply `managed-by` label value to the deployed daemonSet", func() {
```
Comment (oshoval) [inline test/e2e/workflow/deployment_test.go:553]: I think its better to speak in the "positive" terms
Should keep the original managed-by label value
(it is too much oriented to the bug that was, and when time goes by what is important is the current logic)

File: test/e2e/workflow/deployment_test.go [hunk 4]
```diff
@@ -454,6 +455,124 @@ var _ = Describe("NetworkAddonsConfig", func() {
...
+					WithTransform(getDeploymentLabels, HaveKeyWithValue(names.PART_OF_LABEL_KEY, partOfLabelCRVal)),
+					WithTransform(getDeploymentLabels, HaveKeyWithValue(names.VERSION_LABEL_KEY, versionLabelCRVal)),
+					WithTransform(getDeploymentLabels, HaveKeyWithValue(names.COMPONENT_LABEL_KEY, componentLabelCRlVal)),
+					WithTransform(getDeploymentTemplateLabels, HaveKeyWithValue(names.PART_OF_LABEL_KEY, partOfLabelCRVal)),
+					WithTransform(getDeploymentTemplateLabels, HaveKeyWithValue(names.VERSION_LABEL_KEY, versionLabelCRVal)),
+					WithTransform(getDeploymentTemplateLabels, HaveKeyWithValue(names.COMPONENT_LABEL_KEY, componentLabelCRlVal))), "label and template label values of the deployment should be contain the values on NetworkAddonsConfig")
+			})
+		})
+
+		Context("When NetworkAddonsConfig is labeled with `managed-by` label", func() {
```
Comment (oshoval) [inline test/e2e/workflow/deployment_test.go:530]: can the two contexts be merged to one ? 
and directly test all the 4 labels ?

File: test/e2e/workflow/deployment_test.go [hunk 5]
```diff
@@ -454,6 +455,124 @@ var _ = Describe("NetworkAddonsConfig", func() {
...
+			const (
+				managedByLabelCRVal        = "managed-by-cr-value"
+				managedByLabelComponentVal = names.MANAGED_BY_LABEL_DEFAULT_VALUE
```
Comment (oshoval) [inline test/e2e/workflow/deployment_test.go:533]: better to have this line first as this is the default value

File: test/e2e/workflow/deployment_test.go [hunk 6]
```diff
@@ -454,6 +455,124 @@ var _ = Describe("NetworkAddonsConfig", func() {
...
+					err := framework.Global.Client.Get(context.TODO(), types.NamespacedName{Name: OvsComponent.DaemonSets[0], Namespace: components.Namespace}, ovsDaemonSet)
+					Expect(err).ToNot(HaveOccurred(), "should succeed getting the ovs daemonSet")
+					return ovsDaemonSet
+				}, 2*time.Minute, time.Minute).Should(SatisfyAll(
+					WithTransform(getDaemonsetLabels, HaveKeyWithValue(names.PART_OF_LABEL_KEY, partOfLabelCRVal)),
+					WithTransform(getDaemonsetLabels, HaveKeyWithValue(names.VERSION_LABEL_KEY, versionLabelCRVal)),
+					WithTransform(getDaemonsetLabels, HaveKeyWithValue(names.COMPONENT_LABEL_KEY, componentLabelCRlVal)),
+					WithTransform(getDaemonsetTemplateLabels, HaveKeyWithValue(names.PART_OF_LABEL_KEY, partOfLabelCRVal)),
+					WithTransform(getDaemonsetTemplateLabels, HaveKeyWithValue(names.VERSION_LABEL_KEY, versionLabelCRVal)),
+					WithTransform(getDaemonsetTemplateLabels, HaveKeyWithValue(names.COMPONENT_LABEL_KEY, componentLabelCRlVal))), "label and template label values of the daemonset should be contain the values on NetworkAddonsConfig")
```
Comment (oshoval) [inline test/e2e/workflow/deployment_test.go:512]: please consider making this a function , and then this and the next test can be both in one `It` 
that calls this function with parameters (either deployment / ds)

**Review by oshoval — COMMENTED** [review]
Thanks Alon / Ram,

Please check the code smell as well

File: test/operations/operations.go (hunk 1 above)
Comment (RamLavi) [reply test/operations/operations.go:167]: I think you mean that if there are no existing labels, then just do `config.SetLabels(newLabels)`
if that's the case then I prefer to have the action (in our case SetLabels) to be done once on all cases (as much as possible)
To have multiple places where the action is happening is more prone to bugs (fix here, but forget to fix the other...)

File: test/e2e/workflow/deployment_test.go (hunk 2 above)
Comment (RamLavi) [reply test/e2e/workflow/deployment_test.go:479]: I think that simple getters can totally be in onelines, because they're very simple.
anything more complicated should as you say be in regular functions

File: test/e2e/workflow/deployment_test.go (hunk 5 above)
Comment (RamLavi) [reply test/e2e/workflow/deployment_test.go:533]: done

File: test/e2e/workflow/deployment_test.go (hunk 2 above)
Comment (oshoval) [reply test/e2e/workflow/deployment_test.go:479]: imo it is much cleaner and readable to not have inline functions
when you read the file, you dont need to see the functions as first thing,
you see the code, and later extend the view upon need

File: test/e2e/workflow/deployment_test.go (hunk 6 above)
Comment (RamLavi) [reply test/e2e/workflow/deployment_test.go:512]: I would preferably use a function and send it the labels then do `Expect(getDaemonsetLabels).To(ContainElements(expectedLabels)` 
but that is not supported as I want to compare both key+Value and:
```
For maps, ContainElements matches against the map’s values.
so UUIC I can only check it like that...
```

**Comment by RamLavi** [comment]
Hey @oshoval 
I remembered that we don't need e2e tests for this (you already inserted far more extensive unit tests for it.)
remove e2e test
Please re-review :)

**Comment by RamLavi** [comment]
> Thanks Alon / Ram,
> 
> Please check the code smell as well

the code-smell is [referring](test/releases/99.0.0.go) to unrelated tests go file, we can address this in another PR

File: pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go [hunk 7]
```diff
@@ -530,19 +530,20 @@ func updateObjectsLabels(crLables map[string]string, objs []*unstructured.Unstru
 		// Label objects with version of the operator they were created by
 		labels[cnaov1.SchemeGroupVersion.Group+"/version"] = operatorVersionLabel
 		labels[names.PROMETHEUS_LABEL_KEY] = names.PROMETHEUS_LABEL_VALUE
+		labels[names.MANAGED_BY_LABEL_KEY] = names.MANAGED_BY_LABEL_DEFAULT_VALUE
 		err = updateObjectTemplateLabels(obj, labels, []string{names.PROMETHEUS_LABEL_KEY})
```
Comment (oshoval) [inline pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go:534]: we might want to consider please refactor the double call of `updateObjectTemplateLabels`

File: pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go [hunk 8]
```diff
@@ -530,19 +530,16 @@ func updateObjectsLabels(crLables map[string]string, objs []*unstructured.Unstru
...
+		labels[names.MANAGED_BY_LABEL_KEY] = names.MANAGED_BY_LABEL_DEFAULT_VALUE
 
+		appLabelKeys := []string{names.COMPONENT_LABEL_KEY, names.PART_OF_LABEL_KEY, names.VERSION_LABEL_KEY}
 		labels = updateLabelsFromCR(labels, crLables, appLabelKeys)
 		if err != nil {
 			return err
 		}
 		obj.SetLabels(labels)
 
+		appLabelKeys = append(appLabelKeys, names.PROMETHEUS_LABEL_KEY, names.MANAGED_BY_LABEL_KEY)
```
Comment (oshoval) [inline pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go:542]: now that there are 2 additional labels
maybe worth to declare an array of them, the ones that will be added by aren't updated from the CR
and then append this array instead appending individuals ?

File: pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go [hunk 9]
```diff
@@ -530,19 +530,20 @@ func updateObjectsLabels(crLables map[string]string, objs []*unstructured.Unstru
 		// Label objects with version of the operator they were created by
 		labels[cnaov1.SchemeGroupVersion.Group+"/version"] = operatorVersionLabel
 		labels[names.PROMETHEUS_LABEL_KEY] = names.PROMETHEUS_LABEL_VALUE
+		labels[names.MANAGED_BY_LABEL_KEY] = names.MANAGED_BY_LABEL_DEFAULT_VALUE
```
[the remark this answers is not in the document]
Comment (RamLavi) [reply pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go:533]: these labels are together here because they are static. I don't think it's worth spacing between them, the correlation is not strong.

[the remark this answers is not in the document]
Comment (oshoval) [reply pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go:533]: i mean space between them and `appLabelKeys :=` which i think you already added since the comment
(line 534)

File: pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go (hunk 8 above)
Comment (RamLavi) [reply pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go]: you are right, this deserves an individual string array

File: pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (RamLavi) [reply pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go:533]: sorry, not sure what you mean..

[the remark this answers is not in the document]
Comment (oshoval) [reply pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go:533]:
```
...
labels[names.MANAGED_BY_LABEL_KEY] = names.MANAGED_BY_LABEL_DEFAULT_VALUE
# empy line here (already exists i think)
appLabelKeys := []string{names.COMPONENT_LABEL_KEY, names.PART_OF_LABEL_KEY, names.VERSION_LABEL_KEY}
updateLabelsFromCR...
```

File: pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go [hunk 10]
```diff
@@ -530,20 +530,18 @@ func updateObjectsLabels(crLables map[string]string, objs []*unstructured.Unstru
...
+		appLabelKeys := []string{names.COMPONENT_LABEL_KEY, names.PART_OF_LABEL_KEY, names.VERSION_LABEL_KEY}
 		labels = updateLabelsFromCR(labels, crLables, appLabelKeys)
 		if err != nil {
 			return err
 		}
 		obj.SetLabels(labels)
 
-		err = updateObjectTemplateLabels(obj, labels, appLabelKeys)
+		var templateLabelKeys []string
+		templateLabelKeys = append(appLabelKeys, names.PROMETHEUS_LABEL_KEY, names.MANAGED_BY_LABEL_KEY)
```
Comment (oshoval) [inline pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go:543]: please consider doing those two in one line []{appLabelKeys..., names.PROMETHEUS_LABEL_KEY, names.MANAGED_BY_LABEL_KEY} (if it works)

or even just 
```
		templateLabelKeys := append(appLabelKeys, names.PROMETHEUS_LABEL_KEY, names.MANAGED_BY_LABEL_KEY)
```

File: pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (RamLavi) [reply pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go:533]: so.. this is no op? we already have an empty line on L534

[the remark this answers is not in the document]
Comment (oshoval) [reply pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go:533]: yes, since it was added already after the original comment, thanks

[the remark this answers is not in the document]
Comment (RamLavi) [reply pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go:533]: ah, that's why I didn't get what you mean. cool then

**Review by oshoval — APPROVED** [review]
Thanks

**Comment by RamLavi** [comment]
/override pull-e2e-cluster-network-addons-operator-nmstate-functests
unrelated

/approve
