### PR TITLE
e2e/workflow: Fix race waiting for components

### LINKED ISSUE #626: [Flaky CI] NetworkAddonsConfig when there is no pre-existing Config should be able to deploy all components one by one
**What happened**:
prow [link](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/625/pull-e2e-cluster-network-addons-operator-workflow-k8s/1319183344935636992)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
Currently checkConfigChange waiting on the transient status condition of
the CNAO CR, in order to make sure that the component is properly
deployed.
This is raceful by design, as if the component deployment moved "too
fast" to ConditionProgressing=TRUE then the test will fail.
Also, there is another race where the Available condition might change before the operator changed the status to in progress. 

This PR is changing the test to fix these two races.

**Special notes for your reviewer**:
Fix #626

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
unrelated flake, opened an issue.
/retest

File: test/check/check.go [hunk 1]
```diff
@@ -75,6 +75,61 @@ func CheckComponentsRemoval(components []Component) {
...
+	}
+	if configV1.Spec.Multus != nil {
+		existingComponentsMap[MultusComponent.ComponentName] = struct{}{}
+	}
+	if configV1.Spec.MultusDynamicNetworks != nil {
+		existingComponentsMap[MultusDynamicNetworks.ComponentName] = struct{}{}
+	}
+	if configV1.Spec.MultusDynamicNetworks != nil {
+		existingComponentsMap[MultusDynamicNetworks.ComponentName] = struct{}{}
+	}
```
Comment (qinqon) [inline test/check/check.go:114]: dup

File: test/check/check.go [hunk 2]
```diff
@@ -75,6 +75,61 @@ func CheckComponentsRemoval(components []Component) {
 	}
 }
 
+func getConfigComponentsMap(gvk schema.GroupVersionKind) (map[string]struct{}, error) {
```
Comment (qinqon) [inline test/check/check.go:78]: at golang sets are usually expressed as `map[string]bool`

**Review by qinqon — CHANGES_REQUESTED** [review]

File: test/check/check.go (hunk 1 above)
Comment (RamLavi) [reply test/check/check.go:114]: fixed! thanks

File: test/check/check.go (hunk 2 above)
Comment (RamLavi) [reply test/check/check.go:78]: There is no need for a bool, I only want to check if the component is "set" or not. 
IIUC `map[string]struct{}` is idiomatic and preferred in Go when you don't need to store a value, only the presence of a key.

File: test/check/check.go (hunk 1 above)
Comment (oshoval) [reply test/check/check.go:114]: interesting if there is a tool that can detect copy paste dups like this
sometimes it makes bugs, here it was just cosmetics

File: test/check/check.go (hunk 2 above)
Comment (oshoval) [reply test/check/check.go:78]: i also think bool is better

File: test/check/check.go (hunk 1 above)
Comment (RamLavi) [reply test/check/check.go]: perhaps introducing golint will be a good idea for CNAO, but it's not on the near future roadmap as it will take time to refactor the code.

Comment (oshoval) [reply test/check/check.go]: ye no rush about it imho as well

File: test/check/check.go (hunk 2 above)
Comment (oshoval) [reply test/check/check.go:78]:
```
if _, exist := deployedComponents[component.ComponentName]; !exist {
   foo()
}
```

semantic bool is easier to read imho

**Review by qinqon — APPROVED** [review]
/lgtm
/approve

File: test/check/check.go (hunk 2 above)
Comment (RamLavi) [reply test/check/check.go:78]: yeah the boolValue wan't really needed I just wanted to make it more obvious..

Well then I guess it's personal preference. I like struct{} cause it saves memory space, but again it's not super important.

**Comment by RamLavi** [comment]
This fix seems safe to me, and it looks like it fixed the flake. 
backporting to the stable branches

/cherry-pick release-0.79
/cherry-pick release-0.89
/cherry-pick release-0.91
/cherry-pick release-0.93
/cherry-pick release-0.95
/cherry-pick release-0.97

FYI @oshoval
