### PR TITLE
identify OKD4 using NAO

### LINKED ISSUE #189: Missing rbac in network addons
Catching this in the HCO's CI:

```
Wait until cluster-network-addons-operator-6bcb87f966-kgw79 reports Ready condition
error: timed out waiting for the condition
cluster-network-addons-operator-6bcb87f966-kgw79 status has not reached Ready condition within the timeout. Actual state:
2019/07/22 14:19:45 Go Version: go1.11.11
2019/07/22 14:19:45 Go OS/Arch: linux/amd64
2019/07/22 14:19:45 version of operator-sdk: v0.8.0
2019/07/22 14:19:45 version of cluster-network-addons-operator: 0.11.0
2019/07/22 14:19:45 registering Components
2019/07/22 14:19:45 failed setting up operator controllers: failed to check whether running on OpenShift 4: configs.imageregistry.operator.openshift.io is forbidden: User "system:serviceaccount:cluster-network-addons-operator:cluster-network-addons-operator" cannot list configs.imageregistry.operator.openshift.io at the cluster scope
FAILED
```

### PR DESCRIPTION
**Pull request by phoracek**
In order to fix an issue with missing
configs.imageregistry.operator.openshift.io RBAC, let's use NAO
config to identify whether running on OKD4.

Resolves #189

### CODE REVIEW

File: pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go [hunk 1]
```diff
@@ -406,7 +406,7 @@ func getOpenShiftNetworkConfig(ctx context.Context, c k8sclient.Client) (*osv1.N
 // Check whether running on OpenShift 4 by looking for operator objects that has been introduced
 // only in OpenShift 4
 func isRunningOnOpenShift4(c kubernetes.Interface) (bool, error) {
-	return isResourceAvailable(c, "configs", "imageregistry.operator.openshift.io", "v1")
+	return isResourceAvailable(c, "networks", "operator.openshift.io", "v1")
```
Comment (qinqon) [inline pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go]: If you look at node.status.images you have the openshift containers and there the openshift versions is present, maybe it's better to check that:

```yaml

      - docker.io/openshift/origin-node@sha256:7d5efa443cbfff23fb7ac965d50366b237ca4b0e8aabba57f765b58dfa1ddc58
      - docker.io/openshift/origin-node:v3.11.0
      sizeBytes: 1173010592
    - names:
 
```

Comment (SchSeba) [reply pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go]: I think the right way to do it should be make a request to the api server with the `/version` and parse it just like we have the `virtctl version` and the `oc version` commands

Comment (phoracek) [reply pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go]: I agree this is not the best way to check it, but this PR is merely an RBAC bug https://github.com/kubevirt/cluster-network-addons-operator/issues/189 fix that has to be addressed quickly. It doesn't add any functionality, just extends ClusterRole (and on this commented line it switches the object so we can have less RBAC rules). Opened a new issue to track that https://github.com/kubevirt/cluster-network-addons-operator/issues/193.

Would you mind if we leave this as it is?

**Comment by phoracek** [comment]
OpenShift test failed due to a leftover from previous installation. https://kubevirt-master-stdci-production.apps.ovirt.org/job/kubevirt_cluster-network-addons-operator_standard-check-pr/425//artifact/check-patch.lifecycle.os-3.11.0.el7.x86_64/mock_logs/script/stdout_stderr.log

**Comment by phoracek** [comment]
ci test please

File: pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go (hunk 1 above)
Comment (qinqon) [reply pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go]: Ack we can do a follow up to do proper versioning @SchSeba one is the way to go .
